### ISSUE TITLE
Button feedback

### ISSUE THREAD

**Issue by otajor** [vanillasquad/twitter-reviews#27]
The app works well, but it would be better if the user could tell when the button had been clicked. Nothing on the page visibly changes - the button always just looks the same.

Maybe add hover or onclick effects in CSS like this:

``` css
button:hover {
     background-color: blue;
}
```

or 

``` css
/* for onclick effect */
button:active {
     background-color: blue;
}
```
